import { MONGO_COLLECTIONS } from '../adapters/mongo/collectionNames';
import type { SchemaContract } from './types';

export const inventoryItemsContract: SchemaContract = {
  logicalName: 'inventory_items',
  mongoCollection: MONGO_COLLECTIONS.inventoryItems,
  supabaseTable: 'inventory_items',
  idMapping: {
    mongo: '_id',
    supabase: 'id',
    domain: 'id',
    adapterRule: 'Supabase usa id; Mongo usa _id; adapters convertem _id <-> id.',
  },
  fields: [
    '_id',
    'id',
    'store_id',
    'id_int',
    'id_string',
    'code',
    'tag_code',
    'identifier_search_keys',
    'marketplace_name',
    'marketplace_name_normalized',
    'vehicle_brand_name',
    'vehicle_model_name',
    'vehicle_year',
    'stock_quantity',
    'price',
    'marketplace_price',
    'use_default_price',
    'deleted',
    'deleted_at',
    'status',
    'part_category_id',
    'part_category_name',
    'mercado_libre_brasil_category_id',
    'catalog_attributes',
    'shopee_attributes',
    'compatibilities_restrictions',
    'shopee_category_id',
    'shopee_brand_id',
    'vehicle_type',
    'storage_location_id',
    'storage_location_name',
    'storage_location_source',
    'integrations',
    'images',
    'image_ids',
    'image_count',
    'main_image_id',
    'package_height',
    'package_length',
    'package_width',
    'package_weight',
    'description',
    'description_template',
    'created_at',
    'updated_at',
  ],
  indexes: [
    { name: 'store_id_1_id_int_1', key: { store_id: 1, id_int: 1 } },
    { name: 'store_id_1_id_string_1', key: { store_id: 1, id_string: 1 } },
    { name: 'store_id_1_code_1', key: { store_id: 1, code: 1 } },
    { name: 'store_id_1_tag_code_1', key: { store_id: 1, tag_code: 1 } },
    { name: 'store_id_1_identifier_search_keys_1', key: { store_id: 1, identifier_search_keys: 1 } },
    { name: 'store_id_1_status_1', key: { store_id: 1, status: 1 } },
    { name: 'store_id_1_deleted_1', key: { store_id: 1, deleted: 1 } },
    { name: 'store_id_1_storage_location_id_1', key: { store_id: 1, storage_location_id: 1 } },
    { name: 'store_id_1_part_category_id_1', key: { store_id: 1, part_category_id: 1 } },
    { name: 'store_id_1_mercado_libre_brasil_category_id_1', key: { store_id: 1, mercado_libre_brasil_category_id: 1 } },
    { name: 'store_id_1_marketplace_name_normalized_1', key: { store_id: 1, marketplace_name_normalized: 1 } },
    { name: 'store_id_1_primary_anuncio_mlb_id_1', key: { store_id: 1, primary_anuncio_mlb_id: 1 } },
  ],
};
