import { MONGO_COLLECTIONS } from '../adapters/mongo/collectionNames';
import type { SchemaContract } from './types';

export const storageLocationsContract: SchemaContract = {
  logicalName: 'storage_locations',
  mongoCollection: MONGO_COLLECTIONS.storageLocations,
  supabaseTable: 'storage_locations',
  idMapping: {
    mongo: '_id',
    supabase: 'id',
    domain: 'id',
    adapterRule: 'Supabase usa id; Mongo usa _id; adapters convertem _id <-> id.',
  },
  fields: [
    '_id',
    'id',
    'store_id',
    'name',
    'abbreviation',
    'description',
    'status',
    'created_by',
    'created_at',
    'updated_at',
    'stock_capacity',
    'volume_total',
    'quantity_pieces',
    'volume_used',
    'quantity_max_pieces',
    'vehicle_brand_ids',
    'part_category_ids',
    'search_name_ngrams',
    'location_path_names',
    'location_path_slugs',
    'location_path_key',
    'location_path_prefixes',
    'location_path_text',
    'location_path_depth',
    'location_path_character_count',
    'storage_location_type_id',
    'storage_location_type_name',
    'path',
    'path_ids',
    'path_text',
    'path_items',
    'level',
    'rule_overrides',
    'combined_quantity_pieces',
    'combined_volume_used',
    'inferred_quantity_pieces',
    'inferred_volume_used',
  ],
  indexes: [
    { name: 'store_id_1_name_1_status_1', key: { store_id: 1, name: 1, status: 1 } },
    { name: 'store_id_1_location_path_key_1', key: { store_id: 1, location_path_key: 1 } },
    { name: 'store_id_1_path_text_1', key: { store_id: 1, path_text: 1 } },
    { name: 'store_id_1_location_path_text_1', key: { store_id: 1, location_path_text: 1 } },
    { name: 'store_id_1_status_1', key: { store_id: 1, status: 1 } },
  ],
};
